#ifndef CLASES_H
#define CLASES_H
#include <cstdlib>
#include <iostream>
#include <string>
#include <sstream>
using std::cout;
using std::cin;
using std::endl;
using std::string;
using std::stringstream;
#include "abarrote.h"
#include "carne.h"
#include "categoria.h"
#include "conserva.h"
#include "embutido.h"
#include "empaque.h"
#include "fecha.h"
#include "perecedero.h"
#include "prodPerecedero.h"
#include "producto.h"
#include "listaProd.h"
#include "persona.h"
#include "factura.h"
#include "listaClientes.h"
#endif 